### ISSUE TITLE
ERROR: No matching distribution found for onnxruntime==1.11

### ISSUE THREAD

**Issue by wanliAlex** [Lednik7/CLIP-ONNX#10]
Hi, Thanks for the great work!

I am having this error when I try to install the package.

ERROR: No matching distribution found for onnxruntime==1.11

Maybe we can update the requirements.txt?

**Comment by Lednik7** [comment]
Hello, the example in colab works as it should.  Try upgrading pip.

`python -m pip install --upgrade pip`
